### ISSUE TITLE
Text is added

### ISSUE THREAD

**Issue by romgrk** [chemoish/atom-valign#8]
From: (cursor on first character, marked as **|**)
```
|   'enter':     'native!'
    'backspace': 'native!'
    'shift-backspace': 'native!'
    'tab':       'native!'
    'delete':    'native!'
    'insert':    'native!'
    'left':      'native!'
    'right':     'native!'
    'up':        'native!'
    'down':      'native!'
    'pageup':    'native!'
    'pagedown':  'native!'
```

To: (cursor on first line, last character, marked as **|**)
```
    'enter':     'native!'|
    'backspace': 'native!'
    'shift-backspace': 'native!'
    'tab':       'native!'
    'delete':    'native!'
    'insert':    'native!'
    'enter':           'native!'
    'backspace':       'native!'
    'shift-backspace': 'native!'
    'tab':             'native!'
    'delete':          'native!'
    'insert':          'native!'
    'left':            'native!'
    'right':           'native!'
    'up':              'native!'
    'down':            'native!'
    'pageup':          'native!'
    'pagedown':        'native!'
```

Other packages: vim-mode, ex-mode, linter
atom v0.201.0
debian jessie

**Comment by chemoish** [comment]
Interesting… I will have to take a look at this cause I don't know the immediate issue. It seems that if you have 10 lines of text it works ('enter' to the second 'tab'), but including the 'delete' or any lines after that does mess it up.

**Comment by chemoish** [comment]
I figured it out, it has to do with the bad sorting code I wrote. Will address it as soon as I can.

**Comment by romgrk** [comment]
Gut, I like that.

**Comment by chemoish** [comment]
Fixed by https://github.com/chemoish/atom-valign/commit/192bdea7cf5722d355ed5ffae09f0d71118bd94c
